name: "Build and Test"
on:
  push:
    branches: [ master ]

jobs:
  build:
    env:
        CTEST_OUTPUT_ON_FAILURE: ON
        CTEST_PARALLEL_LEVEL: 2
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Dpendencies"
      run: |
        pip3 install conan
        conan --version
        cmake --version
        sudo apt-get install -y libtbb-dev

    - name: "Run Build"
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug
        cmake --build . --config Debug --target my_project
        ./bin/my_project
        
    - name: "Run tests" 
      run: |
        cd build
        conan install ..
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release --target my_project-tests
        ./bin/my_project-tests
